version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root-password
      MONGO_INITDB_DATABASE: admin

    ports:
      - 27017:27017
    volumes:
      - "./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on: 
      - mongodb_container
    environment: 
      MONGO_URL: mongodb://root:root-password@localhost:27017/
    networks:
      - backend

  react_app:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on: 
      - api

    networks:
      - backend